#SPDX-License-Identifier: MIT-0
---
# tasks file for cisco_nxos_configure_bgp
- name: Generate scripts to configure BGP on Cisco Nexus BGW Switches
  template:
    src: cisco_nxos_configure_bgp.j2
    dest: "/home/knzadmin/mylab/cisco_nxos_configure_bgp/files/{{ inventory_hostname }}_bgp.cfg"

- name: Push configuration to configure BGP on Cisco Nexus BGW Switches
  cisco.nxos.nxos_config:
    src: "/home/knzadmin/mylab/cisco_nxos_configure_bgp/files/{{ inventory_hostname }}_bgp.cfg"
    save_when: modified
    