---
- name: Covert interface as layer2
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ item.interface_id }}"
        enabled: true
        mode: layer2
        description: Connected to the client
    state: merged
  loop: "{{ interfaces }}"

- name: Assign vlan to the port
  cisco.nxos.nxos_l2_interfaces:
    config:
      - name: "{{ item.interface_id }}"
        mode: access
        access:
          vlan: "{{ item.vlan_id }}"
    state: merged
  loop: "{{ interfaces }}"
