---
- name: Enable OSPF in DC01
  cisco.nxos.nxos_ospfv2:
    config:
      processes:
        - process_id: 1
          shutdown: false
          maximum_paths: 2
          redistribute:
            - protocol: direct
              route_map: local_network
    state: merged

- name: Configure OSPF on interface in DC01 Leaf Switches
  cisco.nxos.nxos_ospf_interfaces:
    config:
      - name: "{{ item.interface }}"
        address_family:
          - afi: ipv4
            processes:
              - area:
                  area_id: 0.0.0.0
                process_id: 1
            shutdown: false
    state: merged
  loop: "{{ leaf_interfaces }}"