---
- name: Enable OSPF on Spines
  cisco.nxos.nxos_ospfv2:
    config:
      processes:
        - process_id: 1
          shutdown: false
          maximum_paths: 2
          redistribute:
            - protocol: ospf
              id: 2
              route_map: dc2_network
    state: merged

- name: Enable OSPF on Spines
  cisco.nxos.nxos_ospfv2:
    config:
      processes:
        - process_id: 2
          shutdown: false
          maximum_paths: 2
          redistribute:
            - protocol: ospf
              id: 1
              route_map: dc1_network
    state: merged

- name: Configure OSPF on Spine interfaces in DC01
  cisco.nxos.nxos_ospf_interfaces:
    config:
      - name: "{{ item.interface }}"
        address_family:
          - afi: ipv4
            processes:
              - area:
                  area_id: 0.0.0.0
                process_id: 1
            shutdown: false
    state: merged
  loop: "{{ dc1_spine_interfaces }}"

- name: Configure OSPF on Spine interface in DC02
  cisco.nxos.nxos_ospf_interfaces:
    config:
      - name: "{{ item.interface }}"
        address_family:
          - afi: ipv4
            processes:
              - area:
                  area_id: 0.0.0.0
                process_id: 2
            shutdown: false
    state: merged
  loop: "{{ dc2_spine_interfaces }}"