---
- name: Configuring SVIs on leaf01
  when: inventory_hostname == 'leaf03'
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ item.vlan_id }}"
        ipv4:
          - address: "{{ item.ip_address }}"
    state: merged
  loop: "{{ leaf03_svi }}"

- name: Enable the SVI on leaf03
  when: inventory_hostname == 'leaf03'
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ item.vlan_id }}"
        enabled: true
    state: merged
  loop: "{{ leaf03_svi }}"

- name: Configuring HSRP on leaf01
  when: inventory_hostname == 'leaf03'
  cisco.nxos.nxos_hsrp:
        interface: "{{ item.vlan_id }}"
        group: "{{ item.group_id }}"
        preempt: enabled
        priority: 250
        version: 2
        vip: "{{ item.vip }}"
        state: present
  loop: "{{ leaf03_svi }}"

- name: Configuring SVIs on leaf04
  when: inventory_hostname == 'leaf04'
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ item.vlan_id }}"
        ipv4:
          - address: "{{ item.ip_address }}"
    state: merged
  loop: "{{ leaf04_svi }}"

- name: Enable the SVI on leaf04
  when: inventory_hostname == 'leaf04'
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ item.vlan_id }}"
        enabled: true
    state: merged
  loop: "{{ leaf04_svi }}"

- name: Configuring HSRP on leaf04
  when: inventory_hostname == 'leaf04'
  cisco.nxos.nxos_hsrp:
        interface: "{{ item.vlan_id }}"
        group: "{{ item.group_id }}"
        priority: default
        version: 2
        vip: "{{ item.vip }}"
        state: present
  loop: "{{ leaf04_svi }}"
