---
- name: Create prefix-list
  when: inventory_hostname in ['leaf01', 'leaf02']
  cisco.nxos.nxos_prefix_lists:
    config:
      - afi: ipv4
        prefix_lists:
          - name: local_network
            description: To advertise local network
            entries:
              - sequence: "{{ item.id }}"
                action: permit
                prefix: "{{ item.network }}"
    state: merged
  loop: "{{ dc1_networks }}"

- name: Create prefix-list
  when: inventory_hostname in ['leaf03', 'leaf04']
  cisco.nxos.nxos_prefix_lists:
    config:
      - afi: ipv4
        prefix_lists:
          - name: local_network
            description: To advertise local network
            entries:
              - sequence: "{{ item.id }}"
                action: permit
                prefix: "{{ item.network }}"
    state: merged
  loop: "{{ dc2_networks }}"

- name: Create route-map
  cisco.nxos.nxos_route_maps:
    config:
      - route_map: local_network
        entries:
          - sequence: 10
            action: permit
            description: Advertise local network
            match:
              ip:
                address:
                  prefix_lists: local_network
    state: merged
  
