---
- name: Create prefix-list for dc01 networks
  cisco.nxos.nxos_prefix_lists:
    config:
      - afi: ipv4
        prefix_lists:
          - name: dc1_network
            description: To advertise dc01 network
            entries:
              - sequence: "{{ item.id }}"
                action: permit
                prefix: "{{ item.network }}"
    state: merged
  loop: "{{ dc1_networks }}"

- name: Create prefix-list for dc02 networks
  cisco.nxos.nxos_prefix_lists:
    config:
      - afi: ipv4
        prefix_lists:
          - name: dc2_network
            description: To advertise dc02 network
            entries:
              - sequence: "{{ item.id }}"
                action: permit
                prefix: "{{ item.network }}"
    state: merged
  loop: "{{ dc2_networks }}"

- name: Create route-map for dc1 networks
  cisco.nxos.nxos_route_maps:
    config:
      - route_map: dc1_network
        entries:
          - sequence: 10
            action: permit
            description: Advertise dc01 network
            match:
              ip:
                address:
                  prefix_lists: dc1_network
    state: merged

- name: Create route-map for dc2 networks
  cisco.nxos.nxos_route_maps:
    config:
      - route_map: dc2_network
        entries:
          - sequence: 10
            action: permit
            description: Advertise dc02 network
            match:
              ip:
                address:
                  prefix_lists: dc2_network
    state: merged