---
- name: Creating VRF
  cisco.nxos.vrf_global:
    config:
      vrfs:
        - name: keepalive
    state: merged

- name: Enable address families
  cisco.nxos.nxos_vrf_address_family:
    config:
      - name: keepalive
        address_families:
          - afi: ipv4
            safi: unicast
    state: merged

- name: Convert interface to L3
  cisco.nxos.nxos_interfaces:
    config:
      - name: Ethernet1/3
        mode: layer3
        enabled: true
    state: merged
- name: Assign vrf to the interface
  cisco.nxos.nxos_vrf_interface:
    vrf: keepalive
    interface: Ethernet1/3
    state: present

      