---
- name: Configure BGP on spine01 switch
  when: inventory_hostname == 'spine01'
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: "{{ spine01_asn }}"
      neighbors:
        - neighbor_address: "{{ item.ip_address }}"
          remote_as: "{{ item.remote_asn }}"
          shutdown: false
    state: merged
  loop: "{{ spine01_neighbors }}"

- name: Configure BGP on spine02 switch
  when: inventory_hostname == 'spine02'
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: "{{ spine02_asn }}"
      neighbors:
        - neighbor_address: "{{ item.ip_address }}"
          remote_as: "{{ item.remote_asn }}"
          shutdown: false
    state: merged
  loop: "{{ spine02_neighbors }}"

- name: Configure address family for spine01
  when: inventory_hostname == 'spine01'
  cisco.nxos.nxos_bgp_neighbor_address_family:
    config:
        as_number: "{{ spine01_asn }}"
        neighbors:
          - neighbor_address: "{{ item.ip_address }}"
            address_family:
              - afi: ipv4
                safi: unicast
                soft_reconfiguration_inbound:
                  always: true
    state: merged
  loop: "{{ spine01_neighbors }}"

- name: Configure address family for spine02
  when: inventory_hostname == 'spine02'
  cisco.nxos.nxos_bgp_neighbor_address_family:
    config:
        as_number: "{{ spine02_asn }}"
        neighbors:
          - neighbor_address: "{{ item.ip_address }}"
            address_family:
              - afi: ipv4
                safi: unicast
                soft_reconfiguration_inbound:
                  always: true
    state: merged
  loop: "{{ spine02_neighbors }}"

- name: Enable multipath on Spine01
  when: inventory_hostname == 'spine01'
  cisco.nxos.nxos_bgp_address_family:
    config:
      as_number: "{{ spine01_asn }}"
      address_family:
        - afi: ipv4
          safi: unicast
          maximum_paths:
            parallel_paths: 2
    state: merged
  loop: "{{ spine01_neighbors }}"

- name: Enable multipath on Spine02
  when: inventory_hostname == 'spine02'
  cisco.nxos.nxos_bgp_address_family:
    config:
      as_number: "{{ spine02_asn }}"
      address_family:
        - afi: ipv4
          safi: unicast
          maximum_paths:
            parallel_paths: 2
    state: merged
  loop: "{{ spine02_neighbors }}"