#SPDX-License-Identifier: MIT-0
---
# tasks file for cisco_nxos_configure_l3_interface
- name: Generate scripts to configure L3 interfaces on Nexus Switches
  template:
    src: cisco_nxos_configure_l3_interface.j2
    dest: "/home/network-admin/mylab/cisco_nxos_configure_l3_interface/files/{{ inventory_hostname }}_l3_interface.cfg"

- name: Push configuration to configure L3 interfaces on Nexus Switches
  cisco.nxos.nxos_config:
    src: "/home/network-admin/mylab/cisco_nxos_configure_l3_interface/files/{{ inventory_hostname }}_l3_interface.cfg"
    save_when: modified