features:
  - ospf
  - bgp

ospf_neighbors:
  - ospf_interface: Ethernet1/1
    ospf_process_id: 3
    ospf_area_id: 0.0.0.0
  - ospf_interface: Ethernet1/2
    ospf_process_id: 1
    ospf_area_id: 0.0.0.0
  - ospf_interface: Ethernet1/3
    ospf_process_id: 1
    ospf_area_id: 0.0.0.0
  - ospf_interface: Loopback1
    ospf_process_id: 1
    ospf_area_id: 0.0.0.0
  - ospf_interface: Ethernet1/4
    ospf_process_id: 2
    ospf_area_id: 0.0.0.0
  - ospf_interface: Ethernet1/5
    ospf_process_id: 2
    ospf_area_id: 0.0.0.0
  - ospf_interface: Loopback2
    ospf_process_id: 2
    ospf_area_id: 0.0.0.0
  