---
- name: Enable features on Nexus
  hosts: Nexus
  connection: network_cli
  gather_facts: no

- hosts: spine
  tasks:
   - name: Enable BGP on Spines
     cisco.nxos.nxos_feature:
       feature: bgp
       state: enabled

   - name: Enable interface-vlan on Spines
     cisco.nxos.nxos_feature:       
       feature: interface-vlan
       state: enabled

   - name: Enable OSPF on Spines
     cisco.nxos.nxos_feature:
       feature: ospf
       state: enabled

- hosts: leaf
  tasks:
    - name: Enable BGP on Leafs
      cisco.nxos.nxos_feature:
        feature: bgp
        state: enabled

    - name: Enable interface-vlan on Leafs
      cisco.nxos.nxos_feature:
        feature: interface-vlan
        state: enabled

    - name: Enable OSPF on Leafs
      cisco.nxos.nxos_feature:
        feature: ospf
        state: enabled

    - name: Enable HSRP on Leafs
      cisco.nxos.nxos_feature:
        feature: hsrp
        state: enabled

    - name: Enable VPC on Leafs
      cisco.nxos.nxos_feature:
        feature: vpc
        state: enabled

    - name: Enable LACP on Leafs
      cisco.nxos.nxos_feature:
        feature: lacp
        state: enabled

- hosts: access
  tasks:
    - name: Enable LACP on Leafs
      cisco.nxos.nxos_feature:
        feature: lacp
        state: enabled