#SPDX-License-Identifier: MIT-0
---
# tasks file for arista_configure_ospf
- name: Generate scripts to configure OSPF on Arista Spine Switches
  template:
    src: arista_configure_ospf.j2
    dest: "/home/network-admin/mylab/arista_configure_ospf/files/{{ inventory_hostname }}_ospf.cfg"

- name: Push configuration to configure OSPF on Arista Spine Switches
  arista.eos.eos_config:
    src: "/home/network-admin/mylab/arista_configure_ospf/files/{{ inventory_hostname }}_ospf.cfg"
    save_when: modified