interface_config:
  - interface_name: GigabitEthernet2
    ip_address: 10.10.10.1
    subnet_mask: 255.255.255.252
  - interface_name: GigabitEthernet3
    ip_address: 10.10.20.1
    subnet_mask: 255.255.255.252
  - interface_name: loopback0
    ip_address: 10.10.10.10
    subnet_mask: 255.255.255.255

bgp_asn: 100
bgp_config:
  - remote_ip: 11.11.11.11
    remote_asn: 65000
    source_interface: loopback0
  - remote_ip: 12.12.12.12
    remote_asn: 65000
    source_interface: loopback0

  