---
- name: Enable OSPF process on ios
  cisco.ios.ios_ospfv2:
    config:
      processes:
        - process_id: 1

- name: Configure OSPF on the interface
  cisco.ios.ios_ospf_interfaces:
    config:
      - name: GigabitEthernet2
        address_family:
          - afi: ipv4
            process:
              id: 1
              area_id: 0              
            adjacency: true

      - name: GigabitEthernet3
        address_family:
          - afi: ipv4
            process:
              id: 1
              area_id: 0              
            adjacency: true
    state: merged
