---
- name: Enable BGP on nxos
  cisco.nxos.nxos_feature:
    feature: bgp
    state: enabled

- name: Configure BGP
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: "{{ asn }}"
      neighbors:
        - neighbor_address: "{{ neighbors.address }}"
          remote_as: "{{ neighbors.remote_asn }}"

- name: Configure BGP address family
  cisco.nxos.nxos_bgp_neighbor_address_family:
    config:
      as_number: "{{ asn }}"
      neighbors:
        - neighbor_address: "{{ neighbors.address }}"
          address_family:
            - afi: ipv4
              safi: unicast
    state: merged

- name: Redistribute local networks into BGP
  cisco.nxos.nxos_bgp_address_family:
    config:
      as_number: "{{ asn }}"
      address_family:
        - afi: ipv4
          safi: unicast
          networks:
            - prefix: "{{ item.network }}"
    state: merged
  loop: "{{ prefix }}"