---
- name: Creating loopbacks on IOS router
  cisco.ios.ios_l3_interfaces:
    config:
      - name: "{{ item.name }}"
        ipv4:
          - address: "{{ item.ip_address }}"
    state: merged
  loop: "{{ interfaces }}"

- name: Advertising loopbacks in BGP on IOS router
  cisco.ios.ios_bgp_global:
    config:
      as_number: "{{ asn }}"
      networks:
        - address: "{{ item.ip }}"
          netmask: "{{ item.mask }}"
      redistribute:
        - connected:
           set: false
    state: merged
  loop: "{{ ip_mask }}"
