---
- name: Create VLANs on device
  cisco.ios.ios_config:
    lines:
      - vlan {{ item.id }}
      - name {{ item.name }}
  loop: "{{ vlans }}"

tasks/configure_interfaces.yml
---
- name: Configure point-to-point interfaces with IP addresses
  cisco.nxos.nxos_config:
    lines:
      - interface {{ item.name }}
      - ip address {{ item.ip_address }} {{ item.subnet_mask }}
      - no shutdown
  loop: "{{ interfaces }}"
