#SPDX-License-Identifier: MIT-0
---
# tasks file for configure_l3_interface
- name: Generate scripts to configure L3 interfaces on BG-Router, Spine & Leaf switches
  template:
    src: configure_l3_interface.j2
    dest: "/home/knzadmin/mylab/configure_l3_interface/files/{{ inventory_hostname }}_l3_interface.cfg"

- name: Push L3 interface configuration on Spine & Leaf switches
  cisco.nxos.nxos_config:
    src: "/home/knzadmin/mylab/configure_l3_interface/files/{{ inventory_hostname }}_l3_interface.cfg"
  when: inventory_hostname != 'bg-router'

- name: Push L3 interface configuration on BG-Router
  cisco.ios.ios_config:
    src: "/home/knzadmin/mylab/configure_l3_interface/files/{{ inventory_hostname }}_l3_interface.cfg"
  when: inventory_hostname == 'bg-router'