---
- name: Configuring HSRP
  hosts:
    - lab-sw01
    - lab-sw02
  connection: network_cli
  gather_facts: no

  tasks:
  - name: Configuring lab-sw01 as HSRP active
    when: inventory_hostname == 'lab-sw01'
    cisco.nxos.nxos_hsrp_interfaces:
      config:
        - name: VLAN10
          standby:
            version: 2
          standby_options:
            - group_no: 10
              preempt:
                minimum: 1
              priority:
                level: 200
              ip: 
               - virtual_ip: 192.168.10.1

        - name: VLAN20
          standby:
            version: 2
          standby_options:
            - group_no: 20
              preempt:
                minimum: 1
              priority:
                level: 200
              ip: 
               - virtual_ip: 192.168.20.1

  - name: Configuring lab-sw02 as HSRP standby
    when: inventory_hostname == 'lab-sw02'
    cisco.nxos.nxos_hsrp_interfaces:
      config:
        - name: VLAN10
          standby:
            version: 2
          standby_options:
            - group_no: 10
              ip: 
               - virtual_ip: 192.168.10.1
               
        - name: VLAN20
          standby:
            version: 2
          standby_options:
            - group_no: 20
              ip: 
               - virtual_ip: 192.168.20.1
