---
- name: Default interfaces on NXOS
  hosts: lab-sw01
  gather_facts: no
  connection: network_cli
    
  tasks:
  - name: Delete interfaces
    cisco.nxos.nxos_l3_interfaces:
      config:
          - name: Ethernet 1/1
          - name: Ethernet 1/2
          - name: Ethernet 1/3
          - name: Ethernet 1/4
      state: deleted