---
- name: Configuring Layer-3 interfaces
  hosts: spine
  gather_facts: no
  connection: network_cli

  tasks:
  - name: Enable feature interface-vlan
    cisco.nxos.nxos_feature:
      feature: interface-vlan
      state: enabled

  - name: Enable HSRP
    cisco.nxos.nxos_feature:
      feature: hsrp
      state: enabled

  - name: Configure SVI on lab-sw01
    when: inventory_hostname == 'lab-sw01'
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: VLAN10
        ipv4:
          - address: 192.168.10.2/24
      - name: VLAN20
        ipv4:
            - address: 192.168.20.2/24

  - name: Configure SVI on lab-sw02
    when: inventory_hostname == 'lab-sw02'
    cisco.nxos.nxos_l3_interfaces:
      config:
      - name: VLAN10
        ipv4:
          - address: 192.168.10.3/24
      - name: VLAN20
        ipv4:
            - address: 192.168.20.3/24

  - name: Enable Layer-3 interfaces
    cisco.nxos.nxos_interfaces:
      config:
      - name: VLAN10
        enabled: true
      - name: VLAN20
        enabled: true
      state: merged
  
