---
- name: Configure VLAN & trunk interfaces on NXOS
  hosts: leaf
  gather_facts: no
  connection: network_cli

  tasks:
  - name: Configure VLANs
    cisco.nxos.nxos_vlans:
      config:
          - vlan_id: 10
            name: VLAN_10
            mode: ce
            enabled: true
          - vlan_id: 20
            name: VLAN_20
            mode: ce
            enabled: true
      
  - name: Configure trunk port
    cisco.nxos.nxos_l2_interfaces:
      config:
          - name: Ethernet 1/1
            trunk:
              allowed_vlans: 10,20
          - name: Ethernet 1/2
            trunk:
              allowed_vlans: 10,20
      state: merged