configure_vlans:
  - vlan_id: 210
    vlan_name: VLAN210
  - vlan_id: 220
    vlan_name: VLAN220
  - vlan_id: 4094
    vlan_name: MLAG-Local-Interface

configure_vrf:
  - vrf_name: heartbeat
    vrf_interface: Ethernet1

portchannel_id: 100
configure_portchannel:
  - Ethernet2
  - Ethernet3

configure_mlag_portchannel:
  - mlag_portchannel_id: 20
    mlag_portchannel_member: Ethernet4
    mlag_id: 20

configure_prefix_list:
  - prefix_list_seq_number: 10
    prefix_list_network: 192.168.210.0/24
  - prefix_list_seq_number: 20
    prefix_list_network: 192.168.220.0/24

configure_route_map:
  - route_map_seq_number: 10
    route_map_match_list: Advertise-Local-Network

