vpc_portchannel:
  - vpc_interface: Ethernet1/6
    vpc_po_id: 20

ospf_config:
  - ospf_process_id: 2
    ospf_area_id: 0.0.0.0

ospf_interfaces:
  - ospf_int: loopback0
    ospf_process_id: 2
    ospf_area_id: 0.0.0.0
  - ospf_int: ethernet1/1
    ospf_process_id: 2
    ospf_area_id: 0.0.0.0
  - ospf_int: ethernet1/2
    ospf_process_id: 2
    ospf_area_id: 0.0.0.0

local_asn: 65002
local_networks:
  - subnet: 172.16.10.0/24
  - subnet: 172.16.20.0/24