---
#- name: Configure Nexus switches
#  hosts: Nexus
#  connection: network_cli
#  gather_facts: no
#
#- hosts: leaf
#  vars_files: 
#  - vars/vars_vlans.yml
#  tasks:  
#  - name: Configure L2 VLANs on leaf switches
#    import_tasks: tasks/tasks_vlans.yml
#
#- hosts: access
#  vars_files: 
#  - vars/vars_vlans.yml
#  tasks:  
#  - name: Configure L2 VLANs on access switches
#    import_tasks: tasks/tasks_vlans.yml
#
#- hosts: leaf  
#  tasks:
#  - name: Configure keepalive vrf & assign to interface
#    import_tasks: tasks/tasks_vrf.yml
#
#- hosts: active
#  vars_files:
#  - vars/vars_ip_address_active.yml
#  tasks:
#  - name: Assign IP to keepalive interface
#    import_tasks: tasks/tasks_assign_ip_active.yml
#
#- hosts: standby
#  vars_files:
#  - vars/vars_ip_address_standby.yml
#  tasks:
#  - name: Assign IP to keepalive interface
#    import_tasks: tasks/tasks_assign_ip_standby.yml
#
#- hosts: active
#  vars_files:
#  - vars/vars_ip_address_active.yml
#  tasks:
#  - name: Configure VPC on active
#    import_tasks: tasks/tasks_vpc_active.yml
#
#- hosts: standby
#  vars_files:
#  - vars/vars_ip_address_standby.yml
#  tasks:
#  - name: Configure VPC on standby
#    import_tasks: tasks/tasks_vpc_standby.yml
#
#- hosts: leaf
#  vars_files:
#  - vars/vars_vlans.yml
#  tasks:
#  - name: Configure Downstream PO & allow VLANs
#    import_tasks: tasks/tasks_downstream_sw_po.yml
#
#- hosts: access
#  vars_files:
#  - vars/vars_vlans.yml
#  tasks:
#  - name: Configure PO & allow VLANs
#    import_tasks: tasks/tasks_access_sw_po.yml
#
#- hosts: access
#  vars_files:
#  - vars/vars_l2_interface.yml
#  tasks:
#  - name: Configure Access ports
#    import_tasks: tasks/tasks_l2_interfaces.yml
#
#- hosts: spine
#  vars_files:
#  - vars/vars_l3_interfaces.yml
#  tasks:
#    - name: Convert interfaces to layer3 on Spines
#      import_tasks: tasks/tasks_spine_l3_interfaces.yml
#
#- hosts: leaf
#  vars_files:
#  - vars/vars_l3_interfaces.yml
#  tasks:
#    - name: Convert interfaces to layer3 on Leafs
#      import_tasks: tasks/tasks_leaf_l3_interfaces.yml
#
#- hosts: spine
#  vars_files:
#  - vars/vars_spine_p2p_ip.yml
#  tasks:
#    - name: Assign IP Address to Spines P2P interfaces
#      import_tasks: tasks/tasks_spine_p2p_interfaces.yml
#
#- hosts: leaf
#  vars_files:
#  - vars/vars_leaf_p2p_ip.yml
#  tasks:
#    - name: Assign IP Address to Leafs P2P interfaces
#      import_tasks: tasks/tasks_leaf_p2p_interfaces.yml
#
#- hosts: leaf
#  vars_files:
#  - vars/vars_leaf_svi.yml
#  tasks:
#    - name: Configure SVI & HSRP on Leafs
#      import_tasks: tasks/tasks_dc01_leaf_svi.yml
#
#- hosts: leaf
#  vars_files:
#  - vars/vars_leaf_svi.yml
#  tasks:
#    - name: Configure SVI & HSRP on Leafs
#      import_tasks: tasks/tasks_dc02_leaf_svi.yml
#
#- hosts: leaf
#  vars_files:
#  - vars/vars_local_networks.yml
#  tasks:
#    - name: Configure prefix-list & route-map to advertise local dc1_networks
#      import_tasks: tasks/tasks_advertise_networks.yml
#
#- hosts: spine
#  vars_files:
#  - vars/vars_local_networks.yml
#  tasks:
#    - name: Configure prefix-list & route-map to mutually redistribute networks on spines between ospf processes
#      import_tasks: tasks/tasks_redistribute_ospf.yml
#
#- hosts: dc01
#  vars_files:
#  - vars/vars_l3_interfaces.yml
#  tasks:
#    - name: Configure OSPF on DC01 Leafs
#      import_tasks: tasks/tasks_dc1_ospf.yml
#
#- hosts: dc02
#  vars_files:
#  - vars/vars_l3_interfaces.yml
#  tasks:
#    - name: Configure OSPF on DC01 Leafs
#      import_tasks: tasks/tasks_dc2_ospf.yml
#
#- hosts: spine
#  vars_files:
#  - vars/vars_l3_interfaces.yml
#  tasks:
#    - name: Configure OSPF on DC01 Leafs
#      import_tasks: tasks/tasks_spine_ospf.yml

- hosts: spine
  vars_files:
  - vars/vars_bgp_neighbors.yml
  tasks:
    - name: Configure BGP on Spine switches
      import_tasks: tasks/tasks_spine_bgp.yml

- hosts: leaf
  vars_files:
  - vars/vars_bgp_neighbors.yml
  tasks:
    - name: Configure BGP on Leaf switches
      import_tasks: tasks/tasks_leaf_bgp.yml