#SPDX-License-Identifier: MIT-0
---
# tasks file for configure_vlans
- name: Generate scripts to configure Vlans on Access & Leaf switches
  template:
    src: configure_vlans.j2
    dest: "/home/knzadmin/mylab/configure_vlans/files/{{ inventory_hostname }}_vlans.cfg"

- name: Push scripts to configure Vlans on Access & Leaf switches
  cisco.nxos.nxos_config:
    src: "/home/knzadmin/mylab/configure_vlans/files/{{ inventory_hostname }}_vlans.cfg"