#SPDX-License-Identifier: MIT-0
---
# tasks file for trunk_ports
- name: Configure trunk ports on switches
  template:
    src: trunk_interface.j2
    dest: "/home/knzadmin/mylab/trunk_ports/files/{{ inventory_hostname }}_trunk_port.cfg"

- name: Pushing trunk configuration on switches
  cisco.nxos.nxos_config:
    src: "/home/knzadmin/mylab/trunk_ports/files/{{ inventory_hostname }}_trunk_port.cfg"