#SPDX-License-Identifier: MIT-0
---
# tasks file for arista_configure_l3_interface
- name: Generate scripts to configure L3 interface in Arista Switches
  template:
    src: arista_configure_l3_interface.j2
    dest: "/home/network-admin/mylab/arista_configure_l3_interface/files/{{ inventory_hostname }}_l3_interface.cfg"

- name: Push configuration to configure L3 interface in Arista Switches
  arista.eos.eos_config:
    src: "/home/network-admin/mylab/arista_configure_l3_interface/files/{{ inventory_hostname }}_l3_interface.cfg"
    save_when: modified